// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

// Signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const UPDATE_CREDENTIALS = 'UPDATE_CREDENTIALS';

// User details
export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_FAILURE = 'USER_GET_FAILURE';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAILURE = 'USER_DETAILS_FAILURE';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';

export const USER_DOCUMENTS_REQUEST = 'USER_DOCUMENTS_REQUEST';
export const USER_DOCUMENTS_SUCCESS = 'USER_DOCUMENTS_SUCCESS';
export const USER_DOCUMENTS_FAILURE = 'USER_DOCUMENTS_FAILURE';

export const VALIDATE_AUTH_SUCCESS = 'VALIDATE_AUTH_SUCCESS';
export const VALIDATE_AUTH_FAILURE = 'VALIDATE_AUTH_FAILURE';

// Document details
export const DOC_GET_REQUEST = 'DOC_GET_REQUEST';
export const DOC_GET_SUCCESS = 'DOC_GET_SUCCESS';
export const DOC_GET_FAILURE = 'DOC_GET_FAILURE';

export const DOC_CREATE_REQUEST = 'DOC_CREATE_REQUEST';
export const DOC_CREATE_SUCCESS = 'DOC_CREATE_SUCCESS';
export const DOC_CREATE_FAILURE = 'DOC_CREATE_FAILURE';

export const DOC_UPDATE_REQUEST = 'DOC_UPDATE_REQUEST';
export const DOC_UPDATE_SUCCESS = 'DOC_UPDATE_SUCCESS';
export const DOC_UPDATE_FAILURE = 'DOC_UPDATE_FAILURE';

export const DOC_DELETE_REQUEST = 'DOC_DELETE_REQUEST';
export const DOC_DELETE_SUCCESS = 'DOC_DELETE_SUCCESS';
export const DOC_DELETE_FAILURE = 'DOC_DELETE_FAILURE';

export const TOGGLE_CREATE_DOC = 'TOGGLE_CREATE_DOC';
export const TOGGLE_UPDATE_DOC = 'TOGGLE_UPDATE_DOC';
export const TOGGLE_DELETE_DOC = 'TOGGLE_DELETE_DOC';
export const TOGGLE_CLOSE = 'TOGGLE_CLOSE';
